# -*- coding: utf-8 -*-
"""64015172.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxJbeHc9qQq9jkDufh6X8ugPL3YYQXWb

# 🔰 **64015172 เอกรินทร์ องอาจ**

## รวมใบงานทั้งหมดที่ส่งแล้ว : https://shorturl.at/fgkw6

---
# ✅ Lab09 : Recursive

ใบงาน : https://classroom.google.com/u/1/c/NDk3MTYxNzU2NDgy/a/NTY4OTQ5MjY5Nzc4/details

## ตอนที่ 1 : การออกแบบการทำงานและสร้างฟังก์ชันที่ทำงานแบบ Recursive

### def isPalindrome(str):
"""

def isPalindrome(str1):
    if len(str1) <= 1:
        return True
    if str1[0] != str1[-1]:
        return False
    return isPalindrome(str1[1:-1])

print(isPalindrome("abcdcba"))
print(isPalindrome("atoyota"))
print(isPalindrome("kmitl"))
print(isPalindrome("manassanan"))
print(isPalindrome("programming"))
print(isPalindrome("fundamental"))

"""### def isAscending(list_of_integer):"""

def isAscending(list_of_integer, n):
    if n == len(list_of_integer)-1:
        return True
    else:
        if list_of_integer[n] <= list_of_integer[n+1]:
            return isAscending(list_of_integer, n+1)
        else:
            return False

print(isAscending([1, 2, 3, 4, 5, 6, 7], 0))
print(isAscending([3, 4, 2, 5, 6, 1, 2], 0))
print(isAscending([9, 8, 7, 6, 5, 4], 0))
print(isAscending([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5], 0))
print(isAscending([6, 7, 8, 9, 10, 11, 12], 0))
print(isAscending([6, 3, 8, 7, 9, 2, 3, 1, 5], 0))

"""### def group_of_no_1(island_list,point_no):"""

def group_of_no_1(island_list, point_no):
    if point_no < 0 or point_no == len(island_list):
        return 0
    if island_list[point_no] == 1:
        island_list[point_no] = 0
        return 1 + group_of_no_1(island_list, point_no-1) + group_of_no_1(island_list, point_no+1)
    else:
        return 0

print(group_of_no_1([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0], 1))
print(group_of_no_1([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0], 5))
print(group_of_no_1([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1], 4))
print(group_of_no_1([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1], 10))
print(group_of_no_1([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1], 1))
print(group_of_no_1([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], 7))

"""### def valid_parentheses(str):"""

def valid_parentheses(str):
    if str == "":
        return True
    elif str.find("()") != -1:
        return valid_parentheses(str.replace("()", ""))
    else:
        return False


print(valid_parentheses("(()()(())())"))
print(valid_parentheses("((()()"))
print(valid_parentheses("())()()("))
print(valid_parentheses("(((()))((())))"))
print(valid_parentheses("()()(((())))"))
print(valid_parentheses("()"))

"""---
# ✅ Lab08 : Binary and Sequential Search

ใบงาน : https://classroom.google.com/u/0/c/NDk3MTYxNzU2NDgy/a/NTYwODU1MDM1OTA0/details

## โปรแกรมตัวอย่าง
"""

import random
comparecount = 0


def binary_search(arr, low, high, x):

    global comparecount
    if high >= low:
        mid = (high + low) // 2
        if arr[mid] == x:
            return mid
        elif arr[mid] > x:
            comparecount += 1
            print("comparecount = ", comparecount,
                  "low = ", low, "high =", mid-1)
            return binary_search(arr, low, mid - 1, x)
        else:
            comparecount += 1
            print("comparecount = ", comparecount,
                  "low = ", mid+1, "high =", high)
            return binary_search(arr, mid + 1, high, x)
    else:
        return -1


def sequential_search(arr, x):

    global comparecount
    for i in arr:
        comparecount += 1
        if i == x:
            return comparecount
    return -1


datcount = 100000
# incase of sequential search
arr = [random.randint(1, 10000000) for i in range(datcount)]
# in case of binary search
arr = sorted([random.randint(1, 10000000) for i in range(datcount)])
# in case of succesfully search
x = arr[random.randint(1, datcount)]
# in case of unsuccessfully search
x = -1

# worstcase successfully search
x = arr[-1]
print("key =", x)
print("data len = ", len(arr))
# in case of binary search
result = binary_search(arr, 0, len(arr)-1, x)
# incase of sequential search
result = sequential_search(arr, x)
print("compare count = ", comparecount)
if result != -1:
    print("Element is present at index", str(result))
else:
    print("Element is not present in array")

"""---
# ✅ Lab07 : Sorting

ใบงาน : https://classroom.google.com/u/0/c/NDk3MTYxNzU2NDgy/a/NTAyOTcxMjI2NTU4/details

---
# ✅ Lab06 : AVL Tree และ B-Tree

ใบงาน: https://drive.google.com/file/d/1nbOMzhWs0g17EWEvePdA_OOQV7707K_M/view

## Lab06 : Implementation _ Tree 2
"""

#ส่งแล้ว

"""---
# ✅ Lab05 : Implementation _ Tree 1

ใบงาน : https://drive.google.com/file/d/12Wq9c_W0mdfBudCY6vSz8IIrOW75l9FH/view

##ตอนที่ 1 : สร้าง Tree
"""

#@title จากโค้ดตัวอย่าง ให้นักศึกษาดําเนินการดังนี้ 1. สร้าง tree จากโค้ดตัวอย่าง โดย insert ข้อมูลดังนี้ 15,3,16,9,23,11,7,5,34,19,2 2. เรียกใช้งาน PrintTree() เพื่อตรวจสอบข้อมูล
class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
    
    def __str__(self):
        return str(self.data)

class BST:
    def __init__(self):
        self.root = None

    def insert(self, data):
        if self.root is None:
            self.root = Node(data)
        else:
            root = self.root
            while True:
                if data < root.data:
                    if root.left is None:
                        root.left = Node(data)
                        break
                    root = root.left
                else:
                    if root.right is None:
                        root.right = Node(data)
                        break
                    root = root.right
        return self.root
    
    def printTree(self, node, level = 0):
        if node != None:
            self.printTree(node.right, level + 1)
            print('     ' * level, node)
            self.printTree(node.left, level + 1)

T = BST()
inp = [int(i) for i in input('Enter Input : ').split()]
for i in inp:
    root = T.insert(i)
T.printTree(root)

"""##ตอนที่ 2 : in-order , pre-order , and post-order traverse"""

#@title ให้นักศึกษาดําเนินการดังนี้ 1. เพิ่มเติม code ตัวอย่างในโปรแกรมของนักศึกษา ซึ่งฟังก์ชั่น inorderTraversal() จะทําการดึงข้อมูล จาก Tree แบบ in-order traversal แล้วส่งผลลัพธ์กลับในรูปแบบ list 2. เรียกใช้งานฟังก์ชั่นดังกล่าวแล้วแสดงผล list ที่ได้ 3. สร้างฟังก์ชั่น preorderTraversal() และ postorderTraversal() ที่มีการส่ง list ของผลลัพธ์ของการ ทํา pre-order traversal และ post-order traversal กลับมายังโปรแกรมหลักเช่นเดียวกับ inorderTraversal() 4. เรียกใช้งานฟังก์ชั่น preorderTraversal() และ postorderTraversal() แล้วแสดงผล list ที่ได้
text_pre = "Preorder : "
text_in = "Inorder : "
text_post = "Postorder : "
class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
    
    def __str__(self):
        return str(self.data)
class Queue:
    def __init__(self):
        self.items = []
    
    def is_empty(self):
        return len(self.items) == 0
    
    def enqueue(self, data):
        self.items.append(data)

    def dequeue(self):
        if not self.is_empty():
            return self.items.pop(0)

class BST:
    def __init__(self):
        self.root = None
        self.left = None
        self.right = None

    def insert(self, data):
        if self.root is None:
            self.root = Node(data)
        else:
            T = self.root
            while True:
                if data < T.data:
                    if T.left is None:
                        T.left = Node(data)
                        break
                    T = T.left
                else:
                    if T.right is None:
                        T.right = Node(data)
                        break
                    T = T.right
        return self.root
    
    def printTree(self, node, level = 0):
        global text_curr
        if node != None:
            self.printTree(node.right, level + 1)
            print('     ' * level, node)
            self.printTree(node.left, level + 1)
def preorder(root):
    global text_pre  
    if root:  
        text_pre += str(root.data) + " "
        preorder(root.left)  
        preorder(root.right)  
def inorder(root):  
    global text_in
    if root:  
        inorder(root.left)  
        text_in += str(root.data) + " "
        inorder(root.right)  
def postorder(root):  
    global text_post
    if root:  
        postorder(root.left)   
        postorder(root.right)
        text_post += str(root.data) + " "

T = BST()
inp = [int(i) for i in input('Enter Input : ').split()]
for i in inp:
    root = T.insert(i)
preorder(T.root)
print(text_pre)
inorder(T.root)
print(text_in)
postorder(T.root)
print(text_post)

"""##ตอนที่ 3 : Breadth first (Level order)"""

#@title ให้นักศึกษาดําเนินการดังนี้ 1. เพิ่มฟังก์ชั่น breadthFirst() ที่ทําการหาลําดับของข้อมูลใน Tree จาก Root ไปตามแต่ละ level จนถึง level ล่างสุด แล้วส่งผลลัพธ์กลับเป็น list 2. เรียกใช้งานฟังก์ชั่น breadthFirst() แล้วแสดงผล list ที่ได้
text_pre = "Preorder : "
text_in = "Inorder : "
text_post = "Postorder : "
text_pr = "Breadth : "

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
    
    def __str__(self):
        return str(self.data)
class Queue:
    def __init__(self):
        self.items = []
    
    def is_empty(self):
        return len(self.items) == 0
    
    def enqueue(self, data):
        self.items.append(data)

    def dequeue(self):
        if not self.is_empty():
            return self.items.pop(0)

class BST:
    def __init__(self):
        self.root = None
        self.left = None
        self.right = None

    def insert(self, data):
        if self.root is None:
            self.root = Node(data)
        else:
            T = self.root
            while True:
                if data < T.data:
                    if T.left is None:
                        T.left = Node(data)
                        break
                    T = T.left
                else:
                    if T.right is None:
                        T.right = Node(data)
                        break
                    T = T.right
        return self.root
    
    def printTree(self, node, level = 0):
        global text_curr
        if node != None:
            self.printTree(node.right, level + 1)
            print('     ' * level, node)
            self.printTree(node.left, level + 1)
def preorder(root):
    global text_pre  
    if root:  
        text_pre += str(root.data) + " "
        preorder(root.left)  
        preorder(root.right)  
def inorder(root):  
    global text_in
    if root:  
        inorder(root.left)  
        text_in += str(root.data) + " "
        inorder(root.right)  
def postorder(root):  
    global text_post
    if root:  
        postorder(root.left)   
        postorder(root.right)
        text_post += str(root.data) + " "
def bread(root):
    global text_pr
    q = Queue()
    q.enqueue(root)
    while not q.is_empty():
        dQ = q.dequeue()
        text_pr += str(dQ.data) + ' '
        if dQ.left is not None:
            q.enqueue(dQ.left)
        if dQ.right is not None:
            q.enqueue(dQ.right)
    return text_pr

T = BST()
inp = [int(i) for i in input('Enter Input : ').split()]
for i in inp:
    root = T.insert(i)
preorder(T.root)
print(text_pre)
inorder(T.root)
print(text_in)
postorder(T.root)
print(text_post)
bread(T.root)
print(text_pr)

"""---
# ✅ Activity : Implement linklist
"""

#@title ให้นักศึกษาเขียนโปรแกรมสร้าง Link List แล้ว เก็บข้อมูล ABCDEF หลังจากนั้นให้ แทรกข้อมูล XYZ ระหว่าง C,D
class Node:
   def __init__(self, dataval=None):
      self.dataval = dataval
      self.nextval = None
class SLinkedList:
   def __init__(self):
      self.headval = None

# เพิ่มโหนด
   def Inbetween(self,middle_node,newdata):
      if middle_node is None:
         print("ไม่มีโหนดที่เลือก")
         return

      NewNode = Node(newdata)
      NewNode.nextval = middle_node.nextval
      middle_node.nextval = NewNode

# แสดง linked list
   def listprint(self):
      printval = self.headval
      while printval is not None:
         print (printval.dataval)
         printval = printval.nextval

list = SLinkedList()
list.headval = Node("A")
e2 = Node("B")
e3 = Node("C")
e4 = Node("D")
e5 = Node("E")
e6 = Node("F")

list.headval.nextval = e2
e2.nextval = e3
e3.nextval = e4
e4.nextval = e5
e5.nextval = e6

list.Inbetween(e3,"XYZ")

list.listprint()

"""---
# ✅ Activity : Stack Implementation
"""

#@title ให้นักศึกษาเขียนโปรแกรมสร้าง Stack แล้ว Push เก็บข้อมูล A B C D E F Pop ออกจน empty
class Stack:
  def __init__(self, list = None):
    if list == None:
      self.items = []
    else:
      self.items = list
    self.size = len(self.items)

  def __str__(self):
    s = 'stack of '+ str(self.size())+' items : '
    for ele in self.items:
      s += str(ele)+' '
    return s

  def push(self, i):
    self.items.append(i)
    self.size += 1

  def pop(self):
    return self.items.pop()

  def peek(self):
    return self.items[ -1]

  def isEmpty(self):
    return self.items == []
  
  def size(self):
    return len(self.items)

s = Stack(['A', 'B', 'C', 'D', 'E', 'F'])

while s.isEmpty() != True:
  print(s.items)
  print(s.pop())
print(s.isEmpty())

"""---
# ✅ Lab04 : Implement Data Structure (Stack,Queue,LinkList)

ใบงาน : https://drive.google.com/file/d/1-lTpmslyGZ3mT_6x-hIQVy0v9yDDl_O1/view

##ตอนที่ 1 : สร้าง Stack ที่ใช้งานได้2 ทิศทาง (double head stack)
"""

#@title ให้นักศึกษาสร้าง double-head stack ดังรูปที่สามารถนําข้อมูลเข้า-ออก ได้ทั้ง 2 ทิศทาง แล้ว ทดสอบการทํางานโดย 1. นําข้อมูล A,B,C,D เข้าทางด้านซ้าย แล้วนําข้อมูลออกทางด้านซ้ายจนหมด (left push ,left pop) 2. นําข้อมูล A,B,C,D เข้าทางด้านขวา แล้วนําข้อมูลออกทางด้านขวาจนหมด (right push ,right pop) 3. นําข้อมูล A,B,C,D เข้าทางด้านซ้าย แล้วนําข้อมูลออกทางด้านขวาจนหมด (left push ,right pop) 4. นําข้อมูล A,B,C,D เข้าทางด้านขวา แล้วนําข้อมูลออกทางด้านซ้ายจนหมด (right push ,left pop) หมายเหตุ : ถ้านําข้อมูลเข้า - ออก ทางเดียวกันจะทํางานแบบ Stack แต่ถ้านําข้อมูลเข้า-ออก คนละทางจะ กลายเป็น Queue
class Stack:
  def __init__(self):
    self.list_stack = []

  def push_left(self, item = None):
    if item is not None:
      self.list_stack.insert(0,item)
   
  def push_right(self, item = None):
    if item is not None:
      self.list_stack.append(item)

  def stack(self):
    return self.list_stack

  def pop_left(self):
    return self.list_stack.pop(0) if self.list_stack != [] else "No Stack"

  def pop_right(self):
    return self.list_stack.pop() if self.list_stack != [] else "No Stack"

  def size(self):
    return len(self.list_stack)

  def isEmpty(self):
    return self.list_stack == []

s1 = Stack()

s1.push_left("A")
print("Push Left",s1.stack())
s1.push_left("B")
print("Push Left",s1.stack())
s1.push_left("C")
print("Push Left",s1.stack())
s1.push_left("D")
print("Push Left",s1.stack())

print()
s1.push_right("E")
print("Push Righ:",s1.stack())
s1.push_right("F")
print("Push Righ:",s1.stack())
s1.push_right("G")
print("Push Righ:",s1.stack())

print()
for i in range(0,4):
  print("Pop Left:",s1.pop_left())
  print("stack : ",s1.stack())
print()

for i in range(0,3):
  print("Pop Right:",s1.pop_right())
  print("stack : ",s1.stack())
print()
print("stack : ",s1.stack())

"""##ตอนที่ 2 : สร้าง 2D - Linked List"""

#@title ให้นักศึกษาสร้าง 2D-Linked List ดังรูป โดยมีการทํางานพื้นฐานดังนี้ 1. สร้าง constructure ของ Class 2DLinkedList , Class priNode , Class secNode 2. สร้าง Method a. Append_primary(pri_data) สําหรับเพิ่ม primary node เก็บข้อมูล pri_data ต่อท้าย primary link list b. Delete_primary(pri_data) สําหรับลบ primary node ที่เก็บข้อมูล pri_data c. Append_secondary(pri_data , sec_data) สําหรับเพิ่ม secondary node เก็บข้อมูล sec_data ต่อท้าย primary link list ที่เก็บข้อมูล pri_data โดยถ้าไม่มีข้อมูล pri_data จะ ไม่มีการทํางาน d. Delete_secondary(pri_data, sec_data) สําหรับลบ secondary node ที่เก็บข้อมูล sec_data ของ primary link list ที่เก็บข้อมูล pri_data โดยถ้าไม่มีข้อมูล pri_data จะไม่ มีการทํางาน e. Print_List() สําหรับแสดงผลข้อมูลใน List ทั้งหมด โดยจากรูปตัวอย่างจะแสดงผลเป็น A : A1,A2 B : B1,B2 C : C1,C2 3. ทดลอง insert data ให้มี data structure ดังรูปตัวอย่าง แล้วเรียกใช้งาน Print_List() เพื่อ ตรวจสอบผลการ insert ข้อมูล
class priNode:
    def __init__(self, data, pri_next=None, sec_Node=None):
        self.priNode_data = data
        self.pri_next = pri_next
        self.sec_next = sec_Node
    def __str__(self):
        return str(self.priNode_data)


class secNode:
    def __init__(self, data, sec_next=None):
        self.secNode_data = data
        self.sec_next = sec_next
    def __str__(self):
        return str(self.secNode_data)


class LinkedList2D:
    def __init__(self):
        self.Head = None

    def Append_primary(self, pri_data):
        primary = priNode(pri_data)
        if self.Head == None:
            self.Head = primary
        else:
            n = self.Head
            while n.pri_next != None:
                n = n.pri_next
            n.pri_next = primary

    def Delete_primary(self, pri_data):
        next = self.Head
        if self.Head.priNode_data == pri_data:
            next = next.pri_next
            self.Head = next
        while next.pri_next != None:
            if next.pri_next.priNode_data == pri_data:
                after = next.pri_next.pri_next
                if after == None:
                    next.pri_next = None
                else:
                    next.pri_next = after
                break
            next = next.pri_next

    def Append_secondary(self, pri_data, sec_data):

        next_pri = self.Head

        while next_pri != None:
            if next_pri.priNode_data == pri_data:
                break
            next_pri = next_pri.pri_next

        Addnext_secDode = secNode(sec_data)

        if next_pri.sec_next == None:
            next_pri.sec_next = Addnext_secDode
        else:
            while next_pri.sec_next != None:
                next_pri = next_pri.sec_next
            next_pri.sec_next = Addnext_secDode

    def Delete_secondary(self, pri_data, sec_data):
        next_pri_node = self.Head
        while next_pri_node != None:
            if next_pri_node.priNode_data == pri_data:
                break
            next_pri_node = next_pri_node.pri_next

        while next_pri_node != None:
            before = next_pri_node.sec_next
            if next_pri_node.sec_next.secNode_data == sec_data:
                after = before.sec_next
                if after is None:
                    next_pri_node.sec_next = None
                else:
                    next_pri_node.sec_next = after
                break
            next_pri_node = next_pri_node.sec_next

    def Print_List(self):
        p = self.Head
        while p != None:
            print(p, end=":")
            s = p.sec_next
            while s != None:
                print(s, end=",")
                s = s.sec_next
            print("NULL")
            p = p.pri_next
        print("NULL")


l = LinkedList2D()

l.Append_primary("A")
l.Append_primary("B")
l.Append_primary("C")



l.Append_secondary("A", "A1")
l.Append_secondary("B", "B1")
l.Append_secondary("C", "C1")
l.Append_secondary("A", "A2")
l.Append_secondary("B", "B2")
l.Append_secondary("C", "C2")
l.Append_secondary("C", "C3")

#l.Append_secondary("C", "C3")
l.Print_List()
print()

l.Delete_secondary("C","C1")
l.Delete_secondary("C","C3")
l.Delete_primary("B")

l.Print_List()

"""---
# ✅ Activity : Algorithm Analysis (Big-O)
"""

#@title Activity : ให้นักศึกษา หา source code ใน internet แล้วตอบคำถามว่า 1. โปรแกรมนั้น ทำงานอะไร 2. โปรแกรมนั้น มี Big-O เท่าไหร่
words= ["Apple", "Banana", "Car", "Dolphin" ]
for word in words:
  print ("The following lines will print each letters of "+word)
  for letter in word:
    print (letter)
  print("")

#1.ตอบ โปรแกรมแสดงค ําจําก list ทีละบรรทัด
#2.ตอบ O(n^2)

"""---
# ✅ Lab03 : Algorithm Analysis

ใบงาน : https://drive.google.com/file/d/1zVIf7-JuGDU3LcgYYp9dOs0h23oBhVzg/view

## ตอนที่ 1 : Time Calculation

### ข้อ 1 ให้นักศึกษาค้นหา Source Code ใน internet ที่มีการทํางานเดียวกัน 2 โปรแกรม แล้วใช้ฟังก์ชั่นtime() เพื่อตรวจสอบกว่าการทํางานของทั้งสองโปรแกรม มีการใช้เวลาที่แตกต่างกันอย่างไรบ้าง
"""

#@title โปรแกรมที่ 1 :
import time
st = time.time()

Num = int(input("Enter number : "))
listNum = []
string = ""
i = 2
while Num > 1: 
  if Num % i == 0:
    Num = Num / i
    listNum.append(str(i))
  else:
    i += 1
print(listNum)

en = time.time()
elapsed_time = en - st
print('Execution time:', elapsed_time, 'seconds')

#@title โปรแกรมที่ 2 :
import time
st = time.time()

number = int(input("Enter number: "))
numberdiv = 1
checknum = number
checkdiv = number
z = []
while True:
    for i in range(2,number):
      if checkdiv % i == 0:
        numberdiv *= i
        checkdiv /= i
        z.append(str(i))
        break
    if numberdiv == checknum:
      break
print(z)

en = time.time()
elapsed_time = en - st
print('Execution time:', elapsed_time, 'seconds')

"""###ข้อ 2 ให้นักศึกษาทดสอบการทํางานของ ฟังก์ชั่น NearestNeighbors ของ sklearn.neighbors เมื่อมีการเรียกใช้งานเพื่อหา nearest point ของข้อมูลจุดทดสอบจํานวน 1000 จุด ในจุดอ้างอิงทั้งหมด1,000,000 จุด ใน 2 วิธีการคือ การสร้างลูปเพื่อป้อนข้อมูลทดสอบทีละจุด จนครบ 1000 จุด กับการสร้าง list ของจุดทดสอบ แล้วป้อนค่าดังกล่าวให้ library ทํางาน แล้วตอบคําถามว่าความเร็วในการทํางานของโปรแกรมส่วนที่เป็นตัวหนา เขียนโปรแกรมแบบไหนทํางานได้เร็วกว่า และเร็วกว่ากันกี่เท่า"""

#@title โปรแกรมที่ 1 :
import numpy as np
from sklearn.neighbors import NearestNeighbors
import random
import time

r = lambda: random.randint(0,10000)
samples = [[r(),r(),r()] for i in range(1000000)]
testdat = [[r(),r(),r()] for i in range(1000)]
neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(samples)


st = time.time()

detect1 = neigh.kneighbors(testdat)


en = time.time()
elapsed_time = en - st
print('Execution time:', elapsed_time, 'seconds')

#@title โปรแกรมที่ 2 :
import numpy as np
from sklearn.neighbors import NearestNeighbors
import random
import time

r = lambda: random.randint(0,10000)
samples = [[r(),r(),r()] for i in range(1000000)]
testdat = [[r(),r(),r()] for i in range(1000)]
neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(samples)

detect2=[]

st = time.time()
for i in testdat:
  detect2 += neigh.kneighbors([i])

en = time.time()
elapsed_time = en - st
print('Execution time:', elapsed_time, 'seconds')

"""##ตอนที่ 2 : จงหา Big-O ของโปรแกรมต่อไปนี้"""

#@title โปรแกรมที่ 1 :
n = input("input number : ")
n = int(n)
for i in range(1,n,2):
  print(i)

#Big-O = O(n)

#@title โปรแกรมที่ 2 :
n = input("input number : ")
n = int(n)
for x in range(1,n):
  for y in range(n - x):
    print (" ",end="")
  for y in range(1,x + 1):
    print(y,end="")
  for y in range(2,x + 1):
    print(x - y + 1,end="")
  print()

#Big-O = O(n^2)

#@title โปรแกรมที่ 3 :
n = input("input number : ")
n = int(n)
i=1
while i<n:
  print(i)
  i=2*i

#Big-O = O(log n)

"""## ตอนที่ 3 : เขียนโปรแกรมค้นหาข้อมูลให้มี Big-O ตามที่กําหนด"""

#@title ข้อที่ 1 กําหนดให้ตัวแปร data เป็นค่า list ของค่าสุ่ม แล้วให้นักศึกษาเขียนโปรแกรมเรียงตัวเลขใน rnddat จากน้อยไปมากโดยไม่ใช้คําสั่ง sort() โดยให้การทํางานของโปรแกรมนี้มีค่า Big-O เป็น O(n^2)
import random
mddat = [random.randint(1,1000) for i in range(0,10000)]

def Sort(data):
  dataRange = len(data)
  
  while dataRange != 1:
    Max = 0
    setter = 0
    for i in range(dataRange):
      if data[i] >= Max:
        Max = data[i]
        setter = i
    data[setter],data[dataRange - 1] = data[dataRange - 1],data[setter]
    dataRange -=1 
  return data

def Sort2(data):
  dataRange = len(data)
  for a in range(dataRange):
    for b in range(dataRange):
      if data[a] < data[b]:
        data[a],data[b] = data[b],data[a]
  return data

print(Sort(mddat))

#@title ข้อที่ 2 กําหนดให้ตัวแปร data มีค่าเป็น list ของตัวเลข 1-1,000,000 แล้วให้นักศึกษาเขียนโปรแกรมรับ input เป็นตัวเลข 1 ตัวแล้วทําการค้นหาว่ามีตัวเลขดังกล่าวอยู่ที่ตําแหน่งใด โดยให้การทํางานของโปรแกรมนี้มีค่า Big-O เป็น O(log n)
import random
def binarysearch(array, l, r, x):
  if r>= l:
    mid = l+(r-l) // 2
    if array[mid] == x:
      return mid

    elif array[mid] >x:
      return binarysearch(array, l, mid-1, x)

    else:
      return binarysearch(array, mid+1, r, x)
  else:
    return -1

num = int(input("Enter Number : "))
dat = list(range(1,10001))
result = binarysearch(dat, 0, len(dat) -1, num)
if result != 1:
  print(result)
else:
  print('not')

"""---
# ✅ Lab02 : Data Structure and Applications

ใบงาน : https://drive.google.com/file/d/14UWQfrMED-85jpnXKkEXRlXEyHDQ8rGV/view

##ตอนที่ 1 : ให้นักศึกษาทําโจทย์ต่อไปนี้
"""

#@title ข้อ 1 List : ให้นักศึกษาสร้างฟังก์ชั่น remove_even() ซึ่งเป็นฟังก์ชันที่มี 1 parameter เป็น list ของตัวเลขจํานวนเต็ม แล้วฟังก์ชันจะ return ค่า list ที่มีเฉพาะตัวเลขจํานวนคี่เท่านั้น
def remove_even(lst):
  for ev in A:
    if (ev % 2 == 0):
        A.remove(ev)
  return lst
A = [1,2,3,4,5,6,7]
B = remove_even(A)
print(B) #[1,3,5,7]

#@title ข้อ 2 Linked list : ให้นักศึกษาสร้าง Circular Linked list และมีข้อมูลต่อไปนี้
class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

class SLinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      if self.headval == printval.nextval:
        break
      printval = printval.nextval

list = SLinkedList()
list.headval = Node("abcd")
node2 = Node("efgh")
node3 = Node("ijkl")
node4 = Node("mnop")
node5 = Node("qrst")
node6 = Node("uvw")
node7 = Node("xyz")

list.headval.nextval = node2
node2.nextval = node3
node3.nextval = node4
node4.nextval = node5
node5.nextval = node6
node6.nextval = node7
node7.nextval = list.headval

list.listprint()

#@title ข้อ 3 Stack : ให้นักศึกษาใช้list มาสร้าง stack แล้วนํามาใช้เขียนโปรแกรมนําเข้าตัวอักษรของชื่อนักศึกษาลงใน stack แล้วแสดงผลจากหลังมาหน้า (Reverse)
lst_stack = []

name = input("Type your name ::")
for i in name:
  lst_stack.append(i)
print ("Before ::",name)
print("After :: ",end="")

for j in range(len(lst_stack)):
  print (lst_stack.pop(),end="")

#@title ข้อ 4 Tree : ให้นักศึกษาใช้สร้าง Tree เพื่อใช้ในการเรียงลําดับข้อมูล โดยทดสอบป้อนชุดตัวเลขแบบสุ่มแล้วดึงข้อมูลจาก Tree ให้มีการเรียงลําดับจากมากไปน้อย
class Node:
  def __init__(self, data):
    self.left = None
    self.right = None
    self.data = data
  
  def insert(self, data):
    if self.data:
      if data < self.data:
        if self.left is None:
          self.left = Node(data)
        else:
          self.left.insert(data)
      elif data > self.data:
        if self.right is None:
          self.right = Node(data)
        else:
          self.right.insert(data)

  def tree(self):
    if self.right:
       self.right.tree()
    print(self.data, end=" ")
    if self.left:
       self.left.tree()

num = input("Input number ::")
root = Node(num[0])
for i in num:
  root.insert(i)
root.tree()

"""---
# ✅ Lab01 : Google Colab and Python

ใบงาน : https://drive.google.com/file/d/1AiYWfrr1C7IiO5xokOly_qQgsRisBsWF/view

##ตอนที่ 1 : คําสั่งรับ input , output , loop และ condition
"""

#@title ข้อ 1 จากโปรแกรมตัวอย่างมีการทํางานอย่างไร
a = input("input first number ")
b = input("input second number ")
a,b = int(a),int(b)
for i in range(a,b):
  if i%2==1:
    print(i)

#แสดงผลเลขคี่ ตั้งแต่จำนวน a ถึง b

#@title ข้อ 2 ให้นักศึกษาปรับแก้โปรแกรมตัวอย่างให้เป็นโปรแกรมรับตัวเลข 2 ตัวแล้วแสดงผลรวมของตัวเลขตัวแรกถึงตัวสุดท้าย
a = input("input first number ")
b = input("input second number ")
a,b = int(a),int(b)
n = 0
for i in range(a,b+1):
  n = n+i
print(n)

#@title ข้อ 3 ให้นักศึกษาเขียนโปรแกรมรับ input เป็นตัวเลขจํานวนเต็ม 1 ตัว แล้วแสดงผลการแยกตัวประกอบของตัวเลขนั้น
a = int(input("Enter number : "))
factor = []
while a>1:
  for i in range(2,a+1):
    if a%i==0:
      factor.append(i)
      a//=i
      break  
print(*factor,sep=" x ")

#@title ข้อ 4 โปรแกรมรับ input เป็นตัวเลขจํานวนเต็ม 2 จํานวน แล้วจะแสดงผลค่า ห.ร.ม. ของตัวเลข 2 ตัวนั้น
a = int(input("Enter first number :"))
b = int(input("Enter second number :"))
divisor = min(a, b)
while divisor > 0:
    if a%divisor == 0 and b%divisor == 0:
        print('Greatest common divisor = ', divisor)
        break
    divisor -= 1

#@title ข้อ 5 โปรแกรมรับ input เป็นตัวเลขจํานวนเต็ม 1 ตัว แล้วแสดงผลรูปสี่เหลี่ยมจตุรัสกลวงขนาดเท่ากับตัวเลขที่ป้อนบนจอภาพ
side = int(input("Enter number: "))

for i in range(side):
    for n in range(side):
        if(i == 0 or i == side-1 or n == 0 or n == side-1):
            print('*', end = '')
        else:
            print(' ', end = '')
    print()